### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by sergeirocks100** [Ameliorate/track8-program#1]
First, i'd like to apologize for contacting you through opening an issue on a Github project, but you don't have any other way of contact that i'm willing to use.

Anyways, i can't connect to your FTP server anymore because the SSH key got changed, is there any way i can get a new key so that i can connect again?

I've got a Doomworld account at https://www.doomworld.com/profile/30285-sergeirocks100/ you can message me through.

**Comment by Ameliorate** [comment]
Hey, I couldn't get an account set up on doomworld, but here is fine.

I migrated amel.pw to a new server recently, and I didn't know you still used it. I beleive I've got everything set up like it used to, with your old key.

You can email me at amelorate at amel.pw if it doesn't work. I'll also message you if I get doomworld set up.
